[package]
name = "minGRU-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
candle-core = "0.8"
candle-nn = "0.8"
candle-transformers = "0.8"
flate2 = "1.0.34"
hf-hub = "0.3.2"
rand = "0.8.5"
tokenizers = "0.20.3"
