[package]
name = "minGRU-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
candle-core = { git = "https://github.com/huggingface/candle.git", version = "0.7.2"}
candle-nn = { git = "https://github.com/huggingface/candle.git", version = "0.7.2" }
flate2 = "1.0.34"
rand = "0.8.5"
